name = "AlphaStructures"
uuid = "b34a2d8f-0989-4844-9314-dd3cff8ff09b"
authors = ["marteresagh <marteresa28@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Delaunay = "07eb4e4e-0c6d-46ef-bc4e-83d5e5d860a9"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
